/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateLessonArgs } from "./CreateLessonArgs";
import { UpdateLessonArgs } from "./UpdateLessonArgs";
import { DeleteLessonArgs } from "./DeleteLessonArgs";
import { LessonFindManyArgs } from "./LessonFindManyArgs";
import { LessonFindUniqueArgs } from "./LessonFindUniqueArgs";
import { Lesson } from "./Lesson";
import { Track } from "../../track/base/Track";
import { LessonService } from "../lesson.service";

@graphql.Resolver(() => Lesson)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class LessonResolverBase {
  constructor(
    protected readonly service: LessonService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Lesson",
    action: "read",
    possession: "any",
  })
  async _lessonsMeta(
    @graphql.Args() args: LessonFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Lesson])
  @nestAccessControl.UseRoles({
    resource: "Lesson",
    action: "read",
    possession: "any",
  })
  async lessons(@graphql.Args() args: LessonFindManyArgs): Promise<Lesson[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Lesson, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Lesson",
    action: "read",
    possession: "own",
  })
  async lesson(
    @graphql.Args() args: LessonFindUniqueArgs
  ): Promise<Lesson | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Lesson)
  @nestAccessControl.UseRoles({
    resource: "Lesson",
    action: "create",
    possession: "any",
  })
  async createLesson(@graphql.Args() args: CreateLessonArgs): Promise<Lesson> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        track: args.data.track
          ? {
              connect: args.data.track,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Lesson)
  @nestAccessControl.UseRoles({
    resource: "Lesson",
    action: "update",
    possession: "any",
  })
  async updateLesson(
    @graphql.Args() args: UpdateLessonArgs
  ): Promise<Lesson | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          track: args.data.track
            ? {
                connect: args.data.track,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Lesson)
  @nestAccessControl.UseRoles({
    resource: "Lesson",
    action: "delete",
    possession: "any",
  })
  async deleteLesson(
    @graphql.Args() args: DeleteLessonArgs
  ): Promise<Lesson | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Track, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Track",
    action: "read",
    possession: "any",
  })
  async track(@graphql.Parent() parent: Lesson): Promise<Track | null> {
    const result = await this.service.getTrack(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
